# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rotina', models.CharField(max_length=250)),
                ('descricao_rotina', models.CharField(max_length=1000)),
                ('tempo_execucao', models.DateField()),
                ('data_ult_execucao', models.DateTimeField()),
                ('nome_execucao_rotina', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_report', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='executiondashboard',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.ReportTypes'),
        ),
    ]
