# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20170130_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiondashboard',
            name='passo_a_passo_execucao',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
