# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_executiondashboard_passo_a_passo_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.ExecutionDashboard'),
        ),
    ]
