# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20170201_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=90)),
                ('variable_vlue', models.CharField(max_length=90)),
            ],
        ),
    ]
