# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_global_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_variables',
            old_name='variable_vlue',
            new_name='variable_value',
        ),
    ]
